import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Buildings, Printer, Receipt } from '@phosphor-icons/react';
import { Link, useParams } from 'react-router-dom';
import { consolidatedReport, listBusinesses, type BusinessSummary, type ConsolidatedReport } from '../lib/businesses';
import { formatCurrency, formatDate } from '../lib/format';
import { inicioDaSemana, somarDias } from '../lib/reporting';

function lastDay(month:string){const [year,number]=month.split('-').map(Number);return `${month}-${String(new Date(year,number,0).getDate()).padStart(2,'0')}`;}
export default function ExtratoConsolidado(){
  const {tipo='mensal',periodo=''}=useParams(); const [businesses,setBusinesses]=useState<BusinessSummary[]>([]); const [selected,setSelected]=useState<string[]>([]); const [report,setReport]=useState<ConsolidatedReport|null>(null); const [error,setError]=useState('');
  const range=useMemo(()=>{if(tipo==='diario')return {start:periodo,end:periodo};if(tipo==='semanal'){const start=inicioDaSemana(periodo);return {start,end:somarDias(start,6)};}return {start:`${periodo}-01`,end:lastDay(periodo)};},[tipo,periodo]);
  useEffect(()=>{void listBusinesses().then(r=>{setBusinesses(r.businesses);setSelected(r.businesses.map(b=>b.id));}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!selected.length)return;void consolidatedReport(range.start,range.end,selected).then(setReport).catch(e=>setError(e.message));},[range.end,range.start,selected]);
  const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.length===1?current:current.filter(item=>item!==id):[...current,id]);
  return <div className="fade-in print-report space-y-5"><div className="no-print"><Link to="/relatorios" className="inline-flex items-center gap-1 text-xs font-semibold text-ink-soft"><ArrowLeft/>Voltar aos relatórios</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-ledger">Visão geral</p><h2 className="font-display text-2xl font-bold">Extrato {tipo} consolidado</h2><p className="mt-1 text-sm text-ink-soft">{formatDate(range.start)} a {formatDate(range.end)}</p></div><button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-xl border border-line px-4 py-2 text-sm font-bold"><Printer/>Imprimir ou salvar PDF</button></div>
    <fieldset className="mt-4 rounded-xl border border-line bg-paper-raised p-3"><legend className="px-1 text-xs font-bold uppercase tracking-wide text-ink-soft">Negócios somados</legend><div className="flex flex-wrap gap-2">{businesses.map(b=><label key={b.id} className={`cursor-pointer rounded-full border px-3 py-1.5 text-xs font-semibold ${selected.includes(b.id)?'border-ledger bg-ledger/10 text-ledger':'border-line text-ink-soft'}`}><input type="checkbox" className="sr-only" checked={selected.includes(b.id)} onChange={()=>toggle(b.id)}/>{b.name}</label>)}</div></fieldset></div>
    {error&&<p className="rounded-xl bg-stamp/10 p-3 text-sm text-stamp">{error}</p>}
    {report&&<section className="report-sheet rounded-2xl border border-line bg-paper-raised p-5 shadow-sm sm:p-7"><header className="mb-6 border-b-2 border-ink pb-4"><p className="font-ledger text-[10px] font-bold uppercase tracking-[.2em] text-ink-soft">CaixaFácil · Extrato consolidado</p><h1 className="mt-1 font-display text-2xl font-bold">{report.businesses.map(b=>b.name).join(' + ')}</h1><p className="mt-1 text-sm text-ink-soft">Sessões que atravessam períodos entram pela data de cada movimentação; vendas entram pela data da venda.</p></header>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Vendas',report.totals.sales],['Entradas',report.totals.entries],['Saídas',report.totals.outputs],['Saldo',report.totals.entries-report.totals.outputs],['Gorjetas',report.totals.tips],['Fiado recebido',report.totals.creditReceived],['Fiado pendente',report.totals.creditPending],['Despesas fixas',report.totals.fixedExpenses]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-paper p-3"><p className="text-[10px] font-bold uppercase text-ink-soft">{label}</p><p className="mt-1 font-ledger text-lg font-bold">{formatCurrency(Number(value))}</p></div>)}</div>
      <div className="mt-7"><h3 className="mb-3 flex items-center gap-2 font-display text-lg font-bold"><Receipt/>Movimentações do período</h3>{report.statement.length===0?<p className="py-8 text-center text-sm text-ink-soft">Nenhuma movimentação no período.</p>:<div className="divide-y divide-line">{report.statement.map(item=><div key={item.id} className="grid gap-1 py-3 text-sm sm:grid-cols-[100px_1fr_160px_120px]"><span className="text-xs text-ink-soft">{formatDate(item.occurredAt.slice(0,10))}</span><span>{item.description||item.source}</span><span className="inline-flex items-center gap-1 text-xs text-ink-soft"><Buildings/>{item.businessName}</span><span className={`text-right font-ledger font-bold ${item.type==='saida'?'text-stamp':'text-ledger'}`}>{item.type==='saida'?'- ':'+ '}{formatCurrency(item.amount)}</span></div>)}</div>}</div>
    </section>}</div>;
}
