import { useEffect, useState, type FormEvent } from 'react';
import { Buildings, CheckCircle, PencilSimple, Plus, Trash } from '@phosphor-icons/react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { archiveBusiness, createBusiness, listBusinesses, renameBusiness, type BusinessesResponse, type BusinessSummary } from '../lib/businesses';
import { formatCurrency } from '../lib/format';
import { RAMOS_ATUACAO } from '../types';
import Modal from '../components/Modal';

export default function Negocios(){
  const {user,switchBusiness}=useAuth(); const navigate=useNavigate();
  const [result,setResult]=useState<BusinessesResponse|null>(null); const [error,setError]=useState('');
  const [creating,setCreating]=useState(false); const [editing,setEditing]=useState<BusinessSummary|null>(null); const [archiving,setArchiving]=useState<BusinessSummary|null>(null);
  const load=()=>listBusinesses().then(setResult).catch(e=>setError(e instanceof Error?e.message:'Erro ao carregar negócios.'));
  useEffect(()=>{void load();},[]);
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);setError('');try{const created=await createBusiness({name:String(form.get('name')),category:String(form.get('category')),offering:String(form.get('offering'))});setCreating(false);await switchBusiness(created.business.id);navigate('/onboarding');}catch(e){setError(e instanceof Error?e.message:'Erro ao criar negócio.');}};
  const rename=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;try{await renameBusiness(editing.id,String(new FormData(e.currentTarget).get('name')));setEditing(null);await load();}catch(e){setError(e instanceof Error?e.message:'Erro ao renomear.');}};
  const archive=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!archiving)return;try{await archiveBusiness(archiving.id,String(new FormData(e.currentTarget).get('confirmation')));setArchiving(null);await load();}catch(e){setError(e instanceof Error?e.message:'Erro ao arquivar.');}};
  const activate=async(id:string)=>{if(id===user?.tenantId)return;setError('');try{await switchBusiness(id);navigate('/');}catch(e){setError(e instanceof Error?e.message:'Erro ao trocar negócio.');await load();}};
  return <div className="fade-in space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-ledger">Sua conta</p><h2 className="font-display text-2xl font-bold">Meus negócios</h2><p className="mt-1 text-sm text-ink-soft">Cada negócio possui catálogo, caixa, clientes e relatórios independentes.</p></div>
      <button disabled={!result||result.businesses.length>=result.maxBusinesses} onClick={()=>setCreating(true)} className="inline-flex items-center gap-2 rounded-xl bg-ledger px-4 py-2.5 text-sm font-bold text-paper disabled:opacity-40"><Plus size={18}/>Novo negócio</button></header>
    {error&&<p role="alert" className="rounded-xl bg-stamp/10 p-3 text-sm text-stamp">{error}</p>}
    {result&&<><section className="rounded-2xl border border-ledger/20 bg-ledger/5 p-5"><p className="text-xs font-bold uppercase tracking-wide text-ink-soft">Total do mês em todos os negócios</p><p className="mt-2 font-ledger text-3xl font-bold text-ledger-strong dark:text-ledger">{formatCurrency(result.consolidatedMonthRevenue)}</p><p className="mt-2 text-xs text-ink-soft">Soma dos {result.businesses.length} negócios ativos deste login.</p></section>
      <div className="grid gap-3 md:grid-cols-2">{result.businesses.map(b=><article key={b.id} className={`rounded-2xl border bg-paper-raised p-4 ${b.active?'border-ledger shadow-sm':'border-line'}`}>
        <div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-ledger/10 text-ledger"><Buildings size={22}/></span><div className="min-w-0"><h3 className="truncate font-display text-lg font-bold">{b.name}</h3><p className="text-xs text-ink-soft">{b.category} · {b.offering}</p></div></div>{b.active&&<span className="inline-flex items-center gap-1 rounded-full bg-ledger/10 px-2 py-1 text-[11px] font-bold text-ledger"><CheckCircle/>Ativo</span>}</div>
        <dl className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-line/20 p-3"><div><dt className="text-[10px] uppercase text-ink-soft">Hoje</dt><dd className="font-ledger font-bold">{formatCurrency(b.todayRevenue)}</dd></div><div><dt className="text-[10px] uppercase text-ink-soft">Neste mês</dt><dd className="font-ledger font-bold">{formatCurrency(b.monthRevenue)}</dd></div></dl>
        <div className="mt-3 flex gap-2"><button onClick={()=>void activate(b.id)} disabled={b.active} className="flex-1 rounded-lg bg-ledger px-3 py-2 text-xs font-bold text-paper disabled:bg-line disabled:text-ink-soft">{b.active?'Negócio atual':'Acessar'}</button><button aria-label={`Renomear ${b.name}`} onClick={()=>setEditing(b)} className="rounded-lg border border-line p-2 text-ink-soft"><PencilSimple size={18}/></button><button aria-label={`Arquivar ${b.name}`} disabled={b.active} onClick={()=>setArchiving(b)} className="rounded-lg border border-line p-2 text-stamp disabled:opacity-30"><Trash size={18}/></button></div>
      </article>)}</div><p className="text-center text-xs text-ink-soft">{result.businesses.length} de {result.maxBusinesses} negócios utilizados</p></>}
    <Modal open={creating} onClose={()=>setCreating(false)} title="Novo negócio"><form onSubmit={create} className="space-y-4"><label className="block text-sm font-semibold">Nome<input name="name" required maxLength={120} className="mt-1 w-full rounded-lg border border-line bg-paper p-2"/></label><label className="block text-sm font-semibold">Ramo<select name="category" required className="mt-1 w-full rounded-lg border border-line bg-paper p-2">{RAMOS_ATUACAO.map(r=><option key={r}>{r}</option>)}</select></label><label className="block text-sm font-semibold">Tipo<select name="offering" className="mt-1 w-full rounded-lg border border-line bg-paper p-2"><option value="produtos">Produtos</option><option value="servicos">Serviços</option><option value="ambos">Produtos e serviços</option></select></label><button className="w-full rounded-xl bg-ledger py-2.5 font-bold text-paper">Criar negócio</button></form></Modal>
    <Modal open={!!editing} onClose={()=>setEditing(null)} title="Renomear negócio">{editing&&<form onSubmit={rename} className="space-y-4"><input name="name" required defaultValue={editing.name} className="w-full rounded-lg border border-line bg-paper p-2"/><button className="w-full rounded-xl bg-ledger py-2.5 font-bold text-paper">Salvar nome</button></form>}</Modal>
    <Modal open={!!archiving} onClose={()=>setArchiving(null)} title="Arquivar negócio">{archiving&&<form onSubmit={archive} className="space-y-4"><p className="text-sm text-ink-soft">Digite <strong className="text-ink">{archiving.name}</strong> para confirmar. Os dados serão preservados, mas o negócio deixará de aparecer.</p><input name="confirmation" required autoComplete="off" className="w-full rounded-lg border border-stamp/30 bg-paper p-2"/><button className="w-full rounded-xl bg-stamp py-2.5 font-bold text-paper">Arquivar negócio</button></form>}</Modal>
  </div>;
}
