import { useEffect, useState } from 'react';
import { ShieldCheck, UserMinus, UsersThree } from '@phosphor-icons/react';
import Modal from '../../components/Modal';
import { useAuth } from '../../context/AuthContext';
import { listPlatformAdmins, updatePlatformAdminLevel, type AdminLevel, type PlatformAdmin } from '../../lib/admin';

export default function AdminTeam() {
  const { user } = useAuth();
  const [items, setItems] = useState<PlatformAdmin[]>([]);
  const [pending, setPending] = useState<{ admin: PlatformAdmin; level: AdminLevel } | null>(null);
  const [confirmation, setConfirmation] = useState('');
  const [error, setError] = useState<string | null>(null);
  const load = () => listPlatformAdmins().then((result) => setItems(result.items)).catch((value) => setError(value instanceof Error ? value.message : 'Não foi possível carregar a equipe.'));
  useEffect(() => { void load(); }, []);
  const confirm = async () => { if (!pending) return; try { await updatePlatformAdminLevel(pending.admin.id, pending.level, confirmation); setPending(null); setConfirmation(''); await load(); } catch (value) { setError(value instanceof Error ? value.message : 'Não foi possível alterar o acesso.'); } };
  const same = pending && confirmation.trim().normalize('NFKC').toLocaleLowerCase('pt-BR') === pending.admin.name.trim().normalize('NFKC').toLocaleLowerCase('pt-BR');
  return <div className="space-y-6 fade-in"><header><h1 className="font-display text-2xl font-bold">Equipe administrativa</h1><p className="mt-1 text-sm text-ink-soft">SUPERADMIN controla ações destrutivas; SUPPORT consulta contas e redefine senhas.</p></header>{error && <p className="rounded-xl bg-stamp/10 p-3 text-sm font-semibold text-stamp">{error}</p>}<div className="grid gap-3 lg:grid-cols-2">{items.map((admin) => <article key={admin.id} className="rounded-2xl border border-line bg-paper-raised p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="rounded-xl bg-ledger/10 p-2.5 text-ledger-strong dark:text-ledger">{admin.adminLevel === 'SUPERADMIN' ? <ShieldCheck size={21} /> : admin.adminLevel === 'SUPPORT' ? <UsersThree size={21} /> : <UserMinus size={21} />}</span><div><h2 className="font-bold">{admin.name}</h2><p className="text-xs text-ink-soft">{admin.email}</p></div></div><span className="rounded-full bg-line px-2 py-1 text-xs font-bold">{admin.adminLevel}</span></div>{admin.id !== user?.id && <div className="mt-4 flex flex-wrap gap-2 border-t border-line pt-3"><button onClick={() => { setPending({ admin, level: 'SUPPORT' }); setConfirmation(''); }} className="rounded-lg border border-line px-3 py-2 text-xs font-bold">Tornar SUPPORT</button><button onClick={() => { setPending({ admin, level: 'SUPERADMIN' }); setConfirmation(''); }} className="rounded-lg bg-ledger/10 px-3 py-2 text-xs font-bold text-ledger-strong dark:text-ledger">Promover</button><button onClick={() => { setPending({ admin, level: 'REVOKED' }); setConfirmation(''); }} className="rounded-lg bg-stamp/10 px-3 py-2 text-xs font-bold text-stamp">Remover acesso</button></div>}</article>)}</div><Modal open={pending !== null} onClose={() => setPending(null)} title="Alterar acesso administrativo?"><div className="space-y-4"><p className="text-sm text-ink-soft">O papel resultante será <strong>{pending?.level}</strong> e todas as sessões atuais do alvo serão revogadas.</p><label className="block rounded-xl border border-brass/30 bg-brass/5 p-3"><span className="text-xs text-ink-soft">Digite <strong>{pending?.admin.name}</strong> para confirmar.</span><input value={confirmation} onChange={(e) => setConfirmation(e.target.value)} className="mt-2 w-full rounded-lg border border-line bg-paper p-2.5" /></label><div className="flex gap-3"><button onClick={() => setPending(null)} className="flex-1 rounded-lg border border-line px-4 py-2.5 text-sm font-semibold">Cancelar</button><button disabled={!same} onClick={() => void confirm()} className="flex-1 rounded-lg bg-ledger px-4 py-2.5 text-sm font-bold text-paper disabled:opacity-40">Confirmar</button></div></div></Modal></div>;
}
